// <auto-generated />
#nullable disable

using System;
using Energy.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Energy.Api.Migrations;

[DbContext(typeof(EnergyDbContext))]
[Migration("20260402120000_InitialCreate")]
public partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("Energy.Api.Models.EnergyDrink", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("Brand")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("brand");

            b.Property<int?>("Calories")
                .HasColumnType("integer")
                .HasColumnName("calories");

            b.Property<int?>("CaffeineMg")
                .HasColumnType("integer")
                .HasColumnName("caffeine_mg");

            b.Property<string>("Country")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("country");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<DateTime>("ExpirationDate")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("expiration_date");

            b.Property<string>("Flavor")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("flavor");

            b.Property<string>("ImageUrl")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)")
                .HasColumnName("image_url");

            b.Property<bool>("IsActive")
                .HasColumnType("boolean")
                .HasColumnName("is_active");

            b.Property<bool>("IsSugarFree")
                .HasColumnType("boolean")
                .HasColumnName("is_sugar_free");

            b.Property<string>("Line")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("line");

            b.Property<decimal?>("Price")
                .HasPrecision(10, 2)
                .HasColumnType("numeric(10,2)")
                .HasColumnName("price");

            b.Property<int>("Quantity")
                .HasColumnType("integer")
                .HasColumnName("quantity");

            b.Property<int?>("SugarGrams")
                .HasColumnType("integer")
                .HasColumnName("sugar_grams");

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.Property<int>("VolumeMl")
                .HasColumnType("integer")
                .HasColumnName("volume_ml");

            b.HasKey("Id");

            b.HasIndex("Brand");

            b.HasIndex("ExpirationDate");

            b.HasIndex("IsActive");

            b.HasIndex("Brand", "Line", "Flavor", "VolumeMl");

            b.ToTable("energy_drinks", (string)null);
        });
#pragma warning restore 612, 618
    }
}
